import Head from "next/head";
import Search from "../shared/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokefetch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="hero">
          <div className="container">
            <div className="hero-content">
              <div className="hero-left">
                <h1 className="hero-title">Pokefetch</h1>
                <Search />
              </div>
              <div className="hero-right">
                <img
                  src="/pokefetch/images/pokeball.png"
                  alt="Pokemon Pokeball"
                  className="hero-image"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
