import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function Home() {
  const [searchText, setSearchText] = useState('');
  const router = useRouter();

  function handleSubmit(e) {
    e.preventDefault();
    router.push(`/search?pokemon=${searchText}`);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokefetch</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pokefetch</h1>

        <form onSubmit={handleSubmit}>
          <input
            type='text'
            value={searchText}
            onChange={(e) => setSearchText(e.currentTarget.value)}
          />
          <button type='submit'>search</button>
        </form>
      </main>

      <footer className={styles.footer}>@praqo</footer>
    </div>
  );
}
